### ISSUE TITLE
插件不能使用,Flutter2.5,三星S8

### ISSUE THREAD

**Issue by hu70258tao** [arcticfox1919/flutter-scankit#11]
```
======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while de-activating platform stream on channel xyz.bczl.flutter_scankit/event:
MissingPluginException(No implementation found for method cancel on channel xyz.bczl.flutter_scankit/event)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:498:9)
<asynchronous suspension>
====================================================================================================
```

**Comment by hu70258tao** [comment]
再来一个异常
```
../../Android/Flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_easy_permission-1.1.0/lib/flutter_easy_permission.dart:91:25: Error: The method 'checkMethodCallHandler' isn't defined for the class 'MethodChannel'.
 - 'MethodChannel' is from 'package:flutter/src/services/platform_channel.dart' ('../../Android/Flutter/packages/flutter/lib/src/services/platform_channel.dart').
Try correcting the name to the name of an existing method, or defining a method named 'checkMethodCallHandler'.
    if(_callbackChannel.checkMethodCallHandler(null)){
```

**Comment by arcticfox1919** [comment]
@hu70258tao 

这是另一个插件库`flutter_easy_permission`报的错误，原因是新版本SDK在未做任何说明的情况下突然删除了 `MethodChannel`中的'checkMethodCallHandler'方法。

你可以先不使用`flutter_easy_permission`库，使用其他动态权限库处理`scankit`需要的权限，或者使用Flutter 2.2版本编译打包程序

**Comment by hu70258tao** [comment]
> @hu70258tao
> 
> 这是另一个插件库`flutter_easy_permission`报的错误，原因是新版本SDK在未做任何说明的情况下突然删除了 `MethodChannel`中的`checkMethodCallHandler`方法。
> 
> 你可以先不使用`flutter_easy_permission`库，使用其他动态权限库处理`scankit`需要的权限，或者使用Flutter 2.2版本编译打包程序

十分感谢你的回答,第一个控制台异常,但是能正常扫描并解析出二维码内容

**Comment by hu70258tao** [comment]
我想再咨询一下,就不到度提了.在使用自定义View时,ScanKitWidget基本上占据了整个页面.我尝试通过BoxSIze等来限制只在蓝色框框(正方形)内显示摄像头内容,但是实景长宽比验证被挤压,右边没有BoxFit之类的属性来调整呢?

**Comment by hu70258tao** [comment]
刚才我打包release试了下,白屏,debug模式下至少还能扫描出内容.

**Comment by arcticfox1919** [comment]
@hu70258tao 
扫码界面一般都是全屏的，ScanKit库底层未必提供修改尺寸的接口，可以重新调整一下UI设计
