### ISSUE TITLE
部分安卓在打开键盘的页面跳转自定义扫码页面出现闪退

### ISSUE THREAD

**Issue by fire1974** [arcticfox1919/flutter-scankit#38]
**第一段异常日志**

D/ScanKitView(17729): ScanKitView create ...
I/ScanKitRemoteView(17729): onCreate:
D/DeferredLifecycleHelper(17729): IDelegateLifeCycleCall onCreate:
I/NetworkKit_CountryCodeBean(17729): main|null|com.huawei.hms.framework.network.grs.local.model.CountryCodeBean| getVendorCountryCode|39|countryCode by ro.hw.country is: cn
I/NetworkKit_CountryCodeBean(17729): main|null|com.huawei.hms.framework.network.grs.local.model.CountryCodeBean| init|15|get issue_country code from VENDOR_COUNTRY
I/NetworkKit_Cc(17729): main|CountryCodeBean.java|com.huawei.hms.scankit.p.Cc|a|4|getCountryCode unknown
I/e (17729): initCameraConfig:false
I/e (17729): onCreate: CameraManageOncreate
E/HaLogProvider(17729): forbiddenHiLog openHa = false
E/HaLogProvider(17729): forbiddenHiLog.getVenderCountry=cn
I/HaLogProvider(17729): init timer, timer=java.util.Timer@7b3fb8f,moduleName=MLKitCamera I/ScanKitRemoteView(17729): onStart:
D/DeferredLifecycleHelper(17729): IDelegateLifeCycleCall onStart:
I/ScanKitRemoteView(17729): onResume:
D/DeferredLifecycleHelper(17729): IDelegateLifeCycleCall onResume:
I/NetworkKit_CountryCodeBean(17729): main|null|com.huawei.hms.framework.network.grs.local.model.CountryCodeBean| getVendorCountryCode|39|countryCode by ro.hw.country is: cn
I/NetworkKit_CountryCodeBean(17729): main|null|com.huawei.hms.framework.network.grs.local.model.CountryCodeBean| init|15|get issue_country code from VENDOR_COUNTRY
I/NetworkKit_Cc(17729): main|CountryCodeBean.java|com.huawei.hms.scankit.p.Cc|a|4|getCountryCode unknown D/SensorManager(17729): 0x791966b730 addFd fd=145
I/DecorView[](17729): pkgName:com.example.zerobotmobileapp old windowMode:0 new windoMode:1, isFixedSize:false D/MouseWheelSynthesizer(17729): mMoveStepInDp: 64, mMoveStepInPixel: 192, mUpTimeDelayed: 100 D/ViewRootImpl(17729): ViewRootImpl mIsInProductivePCDisplay: false
D/InputEventReceiver(17729): dispatchInputInterval 1000000
I/HiTouch_HiTouchSensor(17729): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(17729): onAttached, package=com.example.zerobotmobileapp, windowType=2030, mIsHiTouchRestricted=true
D/mali_winsys(17729): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
W/CameraManager(17729): CameraManager::initCamera camera is not opened yet
I/CameraManager(17729): findCameraId: 0
I/Camera (17729): open camera: 0, package name: com.example.zerobotmobileapp
D/CameraManager(17729): initCameraParameters previewCameraSize: Point(1920, 1080)
I/CameraManager(17729): setFocusMode: continuous-picture
I/DecodeThread(17729): Hints: {POSSIBLE_FORMATS=[CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, QR_CODE, UPC_A, UPC_E], NEED_RESULT_POINT_CALLBACK=Handler (com.huawei.hms.scankit.a) {5a43b38}}
D/ScankitDecode(17729): use remote decoder
I/ScankitSDK(17729): ScankitSDK Version: SCANLITE2.1.0.300
I/ScankitSDK(17729): context has been inited
I/ScankitDecode(17729): doInBackground:
D/scan-time(17729): start preview time:1653904582269
D/CameraManager(17729): CameraManager::requestPreviewFrame PREVIEW_ONE_SHOT D/OpenGLRenderer(17729): disableOutlineDraw is true
I/DecorView[](17729): pkgName:com.example.zerobotmobileapp old windowMode:0 new windoMode:1, isFixedSize:false D/MouseWheelSynthesizer(17729): mMoveStepInDp: 64, mMoveStepInPixel: 192, mUpTimeDelayed: 100 D/ViewRootImpl(17729): ViewRootImpl mIsInProductivePCDisplay: false
D/InputEventReceiver(17729): dispatchInputInterval 1000000
I/ViewRootImpl(17729): dispatchDetachedFromWindow in doDie
W/libEGL (17729): EGLNativeWindowType 0x7919fe7710 disconnect failed
I/HiTouch_HiTouchSensor(17729): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(17729): onAttached, package=com.example.zerobotmobileapp, windowType=2030, mIsHiTouchRestricted=true
D/mali_winsys(17729): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
W/CameraManager(17729): CameraManager::initCamera camera is not opened yet
E/BufferQueueProducer(17729): [SurfaceTexture-0-17729-3]:855: queueBuffer: BufferQueue has been abandoned E/BufferQueueProducer(17729): [SurfaceTexture-0-17729-3]:855: queueBuffer: BufferQueue has been abandoned E/BufferQueueProducer(17729): [SurfaceTexture-0-17729-3]:855: queueBuffer: BufferQueue has been abandoned E/BufferQueueProducer(17729): [SurfaceTexture-0-17729-3]:855: queueBuffer: BufferQueue has been abandoned E/BufferQueueProducer(17729): [SurfaceTexture-0-17729-3]:855: queueBuffer: BufferQueue has been abandoned E/BufferQueueProducer(17729): [SurfaceTexture-0-17729-3]:855: queueBuffer: BufferQueue has been abandoned E/BufferQueueProducer(17729): [SurfaceTexture-0-17729-3]:855: queueBuffer: BufferQueue has been abandoned
D/CameraManager(17729): initCameraParameters previewCameraSize: Point(1920, 1080) I/CameraManager(17729): setFocusMode: continuous-picture
I/Choreographer(17729): Skipped 32 frames! The application may be doing too much work on its main thread. D/OpenGLRenderer(17729): disableOutlineDraw is true
W/System (17729): A resource failed to call release.

**第二段异常日志**

I/ScanKitRemoteView(23155): onDestroy: 
E/HaLogProvider(23155): forbiddenHiLog openHa = false
E/HaLogProvider(23155): forbiddenHiLog.getVenderCountry=cn
E/HaLogProvider(23155): forbiddenHiLog.getVenderCountry=cn
I/HaLogProvider(23155): cancel timer, timer=java.util.Timer@de1de1c,moduleName=MLKitCamera
I/BlockMonitor(23155): dispatchingThrewException In MainThread
D/AndroidRuntime(23155): Shutting down VM
I/QarthLog(23155): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(23155): [PatchStore] create disable file for com.example.zerobotmobileapp uid is 10424
E/AndroidRuntime(23155): FATAL EXCEPTION: main
E/AndroidRuntime(23155): Process: com.example.zerobotmobileapp, PID: 23155
E/AndroidRuntime(23155): java.lang.RuntimeException: Camera is being used after Camera.release() was called
E/AndroidRuntime(23155): 	at android.hardware.Camera.setHasPreviewCallback(Native Method)
E/AndroidRuntime(23155): 	at android.hardware.Camera.access$600(Camera.java:156)
E/AndroidRuntime(23155): 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1275)
E/AndroidRuntime(23155): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(23155): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(23155): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/AndroidRuntime(23155): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23155): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(23155): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
I/Process (23155): Sending signal. PID: 23155 SIG: 9

具体机型为华为nova6 系统鸿蒙2.0.0.230/三星note10+系统版本安卓10

编译环境
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.4 21F79 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)

**Comment by fire1974** [comment]
小米11，安卓版本12，未出现

**Comment by arcticfox1919** [comment]
第一段日志看,相机打开失败
建议直接下载华为的原生[demo apk](https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Examples/android-sample-code-0000001050734383) 验证一下设备是否存在什么问题
